version: '3'
services:
  app:
    build: .
    ports:
      - "7001:7001"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:8082/webgps
  db:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
